#!/usr/bin/env bash
# Install shell aliases for this flake and its sub-flakes into the login shell.
#
# Existing definitions of these aliases, and any other alias pointing into this
# repo, are replaced. A plain rc file (~/.zshrc, ~/.bashrc) gets a marked block.
# A Home Manager rc file (a symlink into /nix/store) can't be edited, so the
# block goes into home.nix as programs.<shell>.shellAliases, followed by
# `home-manager switch`.
#
# Usage: ./install-aliases.sh [--dry-run] [--shell zsh|bash]
set -euo pipefail

repo=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)

# `--` so flags after the alias reach the program instead of `nix run`.
aliases=(
  "nv=nix run $repo#neovim --"
  "dev=nix develop $repo"
  "cl=nix run $repo#claude --"
  "cld=nix run $repo#claude -- --dangerously-skip-permissions"
  "blender=nix run path:$repo/packages/blender --"
  "kicad=nix run path:$repo/packages/kicad --"
  "steam=nix run path:$repo/packages/steam --"
  "wot=nix run path:$repo/packages/wot --"
)

begin="# >>> dev-flake aliases >>>"
end="# <<< dev-flake aliases <<<"

dry_run=0
shell=$(basename "${SHELL:-}")
while [ $# -gt 0 ]; do
  case $1 in
    --dry-run) dry_run=1 ;;
    --shell)
      shell=${2:?--shell needs zsh or bash}
      shift
      ;;
    -h | --help)
      sed -n '2,10s/^# \{0,1\}//p' "$0"
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      exit 2
      ;;
  esac
  shift
done

case $shell in
  zsh) rc=${ZDOTDIR:-$HOME}/.zshrc ;;
  bash) rc=$HOME/.bashrc ;;
  *)
    echo "unsupported shell '$shell'; pass --shell zsh or --shell bash" >&2
    exit 1
    ;;
esac

names=()
for a in "${aliases[@]}"; do names+=("${a%%=*}"); done

# Value of an alias as currently defined in the rc file, quotes stripped.
current_value() {
  [ -f "$rc" ] || return 0
  sed -nE "s/^[[:space:]]*alias (-- )?$1=//p" "$rc" | tail -n 1 |
    sed -E "s/^'(.*)'\$/\\1/; s/^\"(.*)\"\$/\\1/"
}

# Print FILE without our marked block and without alias lines we own (same
# name, or pointing into this repo). Removed alias lines go to stderr, and
# trailing blank lines are dropped so reruns don't accumulate them.
strip_owned() {
  repo=$repo names=" ${names[*]} " begin=$begin end=$end awk '
    function owned(line,   rest, i, c) {
      rest = line
      while ((i = index(rest, ENVIRON["repo"])) > 0) {
        rest = substr(rest, i + length(ENVIRON["repo"]))
        c = substr(rest, 1, 1)
        if (c !~ /[A-Za-z0-9._-]/) return 1
      }
      return 0
    }
    index($0, ENVIRON["begin"]) { inblock = 1; next }
    inblock { if (index($0, ENVIRON["end"])) inblock = 0; next }
    match($0, /^[ \t]*alias (-- )?[A-Za-z0-9_.:-]+=/) {
      name = substr($0, 1, RLENGTH - 1)
      sub(/^[ \t]*alias (-- )?/, "", name)
      if (index(ENVIRON["names"], " " name " ") || owned($0)) {
        line = $0
        sub(/^[ \t]+/, "", line)
        print "  replacing: " line > "/dev/stderr"
        next
      }
    }
    /^[ \t]*$/ { blanks = blanks $0 "\n"; next }
    { printf "%s", blanks; blanks = ""; print }
  ' "$1"
}

echo "Shell: $shell ($rc)"
uptodate=1
for a in "${aliases[@]}"; do
  name=${a%%=*} value=${a#*=}
  have=$(current_value "$name")
  if [ -z "$have" ]; then
    status=new uptodate=0
  elif [ "$have" = "$value" ]; then
    status=ok
  else
    status=update uptodate=0
  fi
  printf '  %-7s %-8s %s\n' "$status" "$name" "$value"
done

tmp=$(mktemp)
trap 'rm -f "$tmp" "$tmp.new"' EXIT

# Write $tmp.new over TARGET (following symlinks), keeping a .bak copy.
# Returns 1 if nothing changed.
apply() {
  if cmp -s "$1" "$tmp.new"; then
    return 1
  fi
  if [ "$dry_run" = 1 ]; then
    diff -u "$([ -f "$1" ] && echo "$1" || echo /dev/null)" "$tmp.new" || true
    return 1
  fi
  [ -f "$1" ] && cp -p "$1" "$1.bak"
  cat "$tmp.new" >"$1"
}

if [ -L "$rc" ] && [[ $(readlink -f "$rc") == /nix/store/* ]]; then
  hm_config=${XDG_CONFIG_HOME:-$HOME/.config}/home-manager/home.nix
  if [ ! -f "$hm_config" ] || ! command -v home-manager >/dev/null; then
    echo "$rc is generated by Nix, but there is no standalone Home Manager" >&2
    echo "config at $hm_config. Add the aliases above to your Nix config." >&2
    exit 1
  fi
  target=$(readlink -f "$hm_config")
  echo "Managed by Home Manager: updating $target"

  strip_owned "$target" >"$tmp"
  if grep -q 'shellAliases' "$tmp"; then
    echo "$target already sets shellAliases; add the aliases there by hand." >&2
    exit 1
  fi

  block="  $begin"$'\n'"  # Managed by $repo/install-aliases.sh; rerun it instead of editing."
  block+=$'\n'"  programs.$shell.shellAliases = {"
  for a in "${aliases[@]}"; do
    value=${a#*=}
    value=${value//\\/\\\\}
    value=${value//\"/\\\"}
    value=${value//\$\{/\\\$\{}
    block+=$'\n'"    ${a%%=*} = \"$value\";"
  done
  block+=$'\n'"  };"$'\n'"  $end"

  # Insert before the closing brace of the top-level attribute set.
  if ! block=$block awk '
    { lines[NR] = $0 }
    /^}[ \t]*$/ { last = NR }
    END {
      if (!last) exit 1
      for (i = 1; i <= NR; i++) {
        if (i == last) {
          if (lines[i - 1] !~ /^[ \t]*$/) print ""
          print ENVIRON["block"]
        }
        print lines[i]
      }
    }
  ' "$tmp" >"$tmp.new"; then
    echo "could not find the closing '}' of $target" >&2
    exit 1
  fi

  if apply "$target"; then
    if ! home-manager switch; then
      cp -p "$target.bak" "$target"
      echo "home-manager switch failed; restored $target" >&2
      exit 1
    fi
  elif [ "$uptodate" = 0 ] && [ "$dry_run" = 0 ]; then
    # home.nix already has the aliases but the generated rc is stale.
    home-manager switch
  elif [ "$dry_run" = 0 ]; then
    echo "Already installed."
    exit 0
  fi
else
  target=$(readlink -f "$rc")
  if [ -f "$target" ]; then
    strip_owned "$target" >"$tmp"
  elif [ "$dry_run" = 0 ]; then
    touch "$target"
  fi
  {
    cat "$tmp"
    [ -s "$tmp" ] && echo
    echo "$begin"
    for a in "${aliases[@]}"; do
      printf "alias %s='%s'\n" "${a%%=*}" "${a#*=}"
    done
    echo "$end"
  } >"$tmp.new"
  if ! apply "$target" && [ "$dry_run" = 0 ]; then
    echo "Already installed."
    exit 0
  fi
fi

if [ "$dry_run" = 1 ]; then
  echo "Dry run: nothing written."
else
  echo "Done. Run 'exec $shell' or open a new terminal to load the aliases."
fi
